spring.application.name=notes-api
spring.datasource.url=jdbc:postgresql://localhost:5432/notesdb
spring.datasource.username=postgres
spring.datasource.password=7860
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true